name: PHPUnit & Psalm

on: [push]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php: '8.0'
          - php: '8.1'
          - php: '8.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php }}"
          tools: flex

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Waiting for MySQL
        run: |
          while ! mysqladmin ping --host=${{ env.MYSQL_HOST }} --port=${{ env.MYSQL_PORT }} --password=${{ env.MYSQL_PASSWORD }} --silent; do
            sleep 1
          done

      - name: PHPUnit
        run: ./vendor/bin/phpunit
  psalm:
    runs-on: ubuntu-latest

    env:
      php-version: '8.0'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          ini-values: "memory_limit=-1"
          coverage: none

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Psalm
        run: ./vendor/bin/psalm --output-format=github --no-progress
